### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/anaispj-htmlforms#1]
# Revisión - Necesita correcciones :warning:
- [ ] Estilo de código y limpieza
# Feedback
-  @anaispj no tengo código para revisar
## Estilo de código y limpieza
- ¡No hay código!
## Mejores prácticas/comentarios
- 
![Captura de pantalla de 2024-03-14 16-37-38](https://github.com/4GeeksAcademy/anaispj-htmlforms/assets/139759297/570f63f3-648f-4f9d-910c-0af997522cbd)
Recuerda que tienes que subir los cambios a github (`git add . `, `git commit -m "texto informativo" `, `git push origin main`)

**Comment by EduardoHernandezGuzman** [comment]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen proyecto @anaispj ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- El atributo `type` en los elementos `<input>` define el tipo de control de entrada que se mostrará al usuario (pueden ser `text`, `number`, `password`, `email`), ... Revísalos porque en el "CVC" sólo nos tendría que dejar introducir números, en el "First name" y "Last name" sólo nos tendría que dejar introducir texto, etc

**Comment by anaispj** [comment]
Hola! Gracias por la corrección, Edu. He estado mirando lo que me comentas de mejores prácticas porque me sonaba haberlo puesto y a mi si que me aparece el atributo en cada input..., de hecho lo he revisado y no me permite poner texto en la casilla de informacion de la tarjeta. No se si te referias a eso. En la de nombre y apellidos tambien puse text, pero aun asi permite introducir numeros. Gracias de nuevo:)
